using Google.Protobuf;
using Grpc.Core;
using System.Text.Json;
using System.Text.Json.Serialization;
using V6.Rpc;
using V6.Services.P2P;
using V6.Services.Pub;
using V6.Services.Pub.Common;

namespace HalalCloud.RpcClient
{
    [JsonSourceGenerationOptions(
         DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
         PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
         UnmappedMemberHandling = JsonUnmappedMemberHandling.Skip)]
    [JsonSerializable(typeof(BatchOperationRequest))]
    [JsonSerializable(typeof(BatchOperationResponse))]
    [JsonSerializable(typeof(ChangePasswordRequest))]
    [JsonSerializable(typeof(Complaint))]
    [JsonSerializable(typeof(ComplaintDeleteRequest))]
    [JsonSerializable(typeof(ComplaintDeleteResponse))]
    [JsonSerializable(typeof(ComplaintListRequest))]
    [JsonSerializable(typeof(ComplaintListResponse))]
    [JsonSerializable(typeof(DavConfig))]
    [JsonSerializable(typeof(DisconnectRequest))]
    [JsonSerializable(typeof(DisconnectResponse))]
    [JsonSerializable(typeof(DocFilePreview))]
    [JsonSerializable(typeof(DownloadAndPreviewInfo))]
    [JsonSerializable(typeof(FastLookup))]
    [JsonSerializable(typeof(FastLookupRequest))]
    [JsonSerializable(typeof(V6.Services.Pub.File))]
    [JsonSerializable(typeof(FileListRequest))]
    [JsonSerializable(typeof(FileListResponse))]
    [JsonSerializable(typeof(V6.Services.Pub.FileShare))]
    [JsonSerializable(typeof(FileShareDeleteRequest))]
    [JsonSerializable(typeof(FileShareDeleteResponse))]
    [JsonSerializable(typeof(FileShareListRequest))]
    [JsonSerializable(typeof(FileShareListResponse))]
    [JsonSerializable(typeof(GetIceCandidateRequest))]
    [JsonSerializable(typeof(GetIceCandidateResponse))]
    [JsonSerializable(typeof(LastLoginResponse))]
    [JsonSerializable(typeof(LoginRequest))]
    [JsonSerializable(typeof(LoginResponse))]
    [JsonSerializable(typeof(ManageRTCRequest))]
    [JsonSerializable(typeof(ManageRTCResponse))]
    [JsonSerializable(typeof(Meta))]
    [JsonSerializable(typeof(OauthTokenCheckResponse))]
    [JsonSerializable(typeof(OauthTokenResponse))]
    [JsonSerializable(typeof(OfflineTaskDeleteRequest))]
    [JsonSerializable(typeof(OfflineTaskDeleteResponse))]
    [JsonSerializable(typeof(OfflineTaskListRequest))]
    [JsonSerializable(typeof(OfflineTaskListResponse))]
    [JsonSerializable(typeof(OrderByInfo))]
    [JsonSerializable(typeof(ParseFileSliceResponse))]
    [JsonSerializable(typeof(ReceiveRequest))]
    [JsonSerializable(typeof(ReceiveResponse))]
    [JsonSerializable(typeof(RegisterRequest))]
    [JsonSerializable(typeof(RpcHeaderValue))]
    [JsonSerializable(typeof(RpcMetaData))]
    [JsonSerializable(typeof(RpcTransport))]
    [JsonSerializable(typeof(RtcPeerInfo))]
    [JsonSerializable(typeof(ScanListRequest))]
    [JsonSerializable(typeof(SearchRequest))]
    [JsonSerializable(typeof(SendIceCandidateRequest))]
    [JsonSerializable(typeof(SendIceCandidateResponse))]
    [JsonSerializable(typeof(SendPeerIceCandidateRequest))]
    [JsonSerializable(typeof(SendPeerIceCandidateResponse))]
    [JsonSerializable(typeof(SftpConfig))]
    [JsonSerializable(typeof(Slice))]
    [JsonSerializable(typeof(SliceDownloadAddressRequest))]
    [JsonSerializable(typeof(SliceDownloadAddressResponse))]
    [JsonSerializable(typeof(SliceDownloadInfo))]
    [JsonSerializable(typeof(SliceSize))]
    [JsonSerializable(typeof(SmsVeifyCodeSendRequest))]
    [JsonSerializable(typeof(SmsVeifyCodeSendRequestNotUser))]
    [JsonSerializable(typeof(SmsVeifyCodeSendResponse))]
    [JsonSerializable(typeof(StartDownloadRequest))]
    [JsonSerializable(typeof(StartDownloadResponse))]
    [JsonSerializable(typeof(StopDownloadRequest))]
    [JsonSerializable(typeof(StopDownloadResponse))]
    [JsonSerializable(typeof(TaskFile))]
    [JsonSerializable(typeof(TaskMeta))]
    [JsonSerializable(typeof(TaskParseRequest))]
    [JsonSerializable(typeof(TaskParseResponse))]
    [JsonSerializable(typeof(Token))]
    [JsonSerializable(typeof(UploadToken))]
    [JsonSerializable(typeof(User))]
    [JsonSerializable(typeof(UserNameValidateResponse))]
    [JsonSerializable(typeof(UserTask))]
    [JsonSerializable(typeof(UserValidateInfo))]
    internal partial class JsonContext : JsonSerializerContext
    {
        private static Marshaller<string> CreateMarshaller<T>() where T : new()
        {
            return new Marshaller<string>(
                (Source) =>
                {
                    IMessage Message = (IMessage)JsonSerializer.Deserialize(
                        Source,
                        typeof(T),
                        Default)!;
                    return Message.ToByteArray();
                },
                (Source) =>
                {
                    IMessage Message = (IMessage)new T();
                    Message.MergeFrom(Source);
                    return JsonSerializer.Serialize(
                        Message,
                        typeof(T),
                        Default);
                });
        }

        public static Dictionary<string, Marshaller<string>> Marshallsers =
           new Dictionary<string, Marshaller<string>>()
           {
                                {
                    "BatchOperationRequest",
                    CreateMarshaller<BatchOperationRequest>()
                },
                {
                    "BatchOperationResponse",
                    CreateMarshaller<BatchOperationResponse>()
                },
                {
                    "ChangePasswordRequest",
                    CreateMarshaller<ChangePasswordRequest>()
                },
                {
                    "Complaint",
                    CreateMarshaller<Complaint>()
                },
                {
                    "ComplaintDeleteRequest",
                    CreateMarshaller<ComplaintDeleteRequest>()
                },
                {
                    "ComplaintDeleteResponse",
                    CreateMarshaller<ComplaintDeleteResponse>()
                },
                {
                    "ComplaintListRequest",
                    CreateMarshaller<ComplaintListRequest>()
                },
                {
                    "ComplaintListResponse",
                    CreateMarshaller<ComplaintListResponse>()
                },
                {
                    "DavConfig",
                    CreateMarshaller<DavConfig>()
                },
                {
                    "DisconnectRequest",
                    CreateMarshaller<DisconnectRequest>()
                },
                {
                    "DisconnectResponse",
                    CreateMarshaller<DisconnectResponse>()
                },
                {
                    "DocFilePreview",
                    CreateMarshaller<DocFilePreview>()
                },
                {
                    "DownloadAndPreviewInfo",
                    CreateMarshaller<DownloadAndPreviewInfo>()
                },
                {
                    "FastLookup",
                    CreateMarshaller<FastLookup>()
                },
                {
                    "FastLookupRequest",
                    CreateMarshaller<FastLookupRequest>()
                },
                {
                    "File",
                    CreateMarshaller<V6.Services.Pub.File>()
                },
                {
                    "FileListRequest",
                    CreateMarshaller<FileListRequest>()
                },
                {
                    "FileListResponse",
                    CreateMarshaller<FileListResponse>()
                },
                {
                    "FileShare",
                    CreateMarshaller<V6.Services.Pub.FileShare>()
                },
                {
                    "FileShareDeleteRequest",
                    CreateMarshaller<FileShareDeleteRequest>()
                },
                {
                    "FileShareDeleteResponse",
                    CreateMarshaller<FileShareDeleteResponse>()
                },
                {
                    "FileShareListRequest",
                    CreateMarshaller<FileShareListRequest>()
                },
                {
                    "FileShareListResponse",
                    CreateMarshaller<FileShareListResponse>()
                },
                {
                    "GetIceCandidateRequest",
                    CreateMarshaller<GetIceCandidateRequest>()
                },
                {
                    "GetIceCandidateResponse",
                    CreateMarshaller<GetIceCandidateResponse>()
                },
                {
                    "LastLoginResponse",
                    CreateMarshaller<LastLoginResponse>()
                },
                {
                    "LoginRequest",
                    CreateMarshaller<LoginRequest>()
                },
                {
                    "LoginResponse",
                    CreateMarshaller<LoginResponse>()
                },
                {
                    "ManageRTCRequest",
                    CreateMarshaller<ManageRTCRequest>()
                },
                {
                    "ManageRTCResponse",
                    CreateMarshaller<ManageRTCResponse>()
                },
                {
                    "Meta",
                    CreateMarshaller<Meta>()
                },
                {
                    "OauthTokenCheckResponse",
                    CreateMarshaller<OauthTokenCheckResponse>()
                },
                {
                    "OauthTokenResponse",
                    CreateMarshaller<OauthTokenResponse>()
                },
                {
                    "OfflineTaskDeleteRequest",
                    CreateMarshaller<OfflineTaskDeleteRequest>()
                },
                {
                    "OfflineTaskDeleteResponse",
                    CreateMarshaller<OfflineTaskDeleteResponse>()
                },
                {
                    "OfflineTaskListRequest",
                    CreateMarshaller<OfflineTaskListRequest>()
                },
                {
                    "OfflineTaskListResponse",
                    CreateMarshaller<OfflineTaskListResponse>()
                },
                {
                    "OrderByInfo",
                    CreateMarshaller<OrderByInfo>()
                },
                {
                    "ParseFileSliceResponse",
                    CreateMarshaller<ParseFileSliceResponse>()
                },
                {
                    "ReceiveRequest",
                    CreateMarshaller<ReceiveRequest>()
                },
                {
                    "ReceiveResponse",
                    CreateMarshaller<ReceiveResponse>()
                },
                {
                    "RegisterRequest",
                    CreateMarshaller<RegisterRequest>()
                },
                {
                    "RpcHeaderValue",
                    CreateMarshaller<RpcHeaderValue>()
                },
                {
                    "RpcMetaData",
                    CreateMarshaller<RpcMetaData>()
                },
                {
                    "RpcTransport",
                    CreateMarshaller<RpcTransport>()
                },
                {
                    "RtcPeerInfo",
                    CreateMarshaller<RtcPeerInfo>()
                },
                {
                    "ScanListRequest",
                    CreateMarshaller<ScanListRequest>()
                },
                {
                    "SearchRequest",
                    CreateMarshaller<SearchRequest>()
                },
                {
                    "SendIceCandidateRequest",
                    CreateMarshaller<SendIceCandidateRequest>()
                },
                {
                    "SendIceCandidateResponse",
                    CreateMarshaller<SendIceCandidateResponse>()
                },
                {
                    "SendPeerIceCandidateRequest",
                    CreateMarshaller<SendPeerIceCandidateRequest>()
                },
                {
                    "SendPeerIceCandidateResponse",
                    CreateMarshaller<SendPeerIceCandidateResponse>()
                },
                {
                    "SftpConfig",
                    CreateMarshaller<SftpConfig>()
                },
                {
                    "Slice",
                    CreateMarshaller<Slice>()
                },
                {
                    "SliceDownloadAddressRequest",
                    CreateMarshaller<SliceDownloadAddressRequest>()
                },
                {
                    "SliceDownloadAddressResponse",
                    CreateMarshaller<SliceDownloadAddressResponse>()
                },
                {
                    "SliceDownloadInfo",
                    CreateMarshaller<SliceDownloadInfo>()
                },
                {
                    "SliceSize",
                    CreateMarshaller<SliceSize>()
                },
                {
                    "SmsVeifyCodeSendRequest",
                    CreateMarshaller<SmsVeifyCodeSendRequest>()
                },
                {
                    "SmsVeifyCodeSendRequestNotUser",
                    CreateMarshaller<SmsVeifyCodeSendRequestNotUser>()
                },
                {
                    "SmsVeifyCodeSendResponse",
                    CreateMarshaller<SmsVeifyCodeSendResponse>()
                },
                {
                    "StartDownloadRequest",
                    CreateMarshaller<StartDownloadRequest>()
                },
                {
                    "StartDownloadResponse",
                    CreateMarshaller<StartDownloadResponse>()
                },
                {
                    "StopDownloadRequest",
                    CreateMarshaller<StopDownloadRequest>()
                },
                {
                    "StopDownloadResponse",
                    CreateMarshaller<StopDownloadResponse>()
                },
                {
                    "TaskFile",
                    CreateMarshaller<TaskFile>()
                },
                {
                    "TaskMeta",
                    CreateMarshaller<TaskMeta>()
                },
                {
                    "TaskParseRequest",
                    CreateMarshaller<TaskParseRequest>()
                },
                {
                    "TaskParseResponse",
                    CreateMarshaller<TaskParseResponse>()
                },
                {
                    "Token",
                    CreateMarshaller<Token>()
                },
                {
                    "UploadToken",
                    CreateMarshaller<UploadToken>()
                },
                {
                    "User",
                    CreateMarshaller<User>()
                },
                {
                    "UserNameValidateResponse",
                    CreateMarshaller<UserNameValidateResponse>()
                },
                {
                    "UserTask",
                    CreateMarshaller<UserTask>()
                },
                {
                    "UserValidateInfo",
                    CreateMarshaller<UserValidateInfo>()
                },

           };
    }
}
